#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stddef.h>

extern "C" {

uint32_t rust_SRCWRUTIL_GetSHA1_File(IFileObject *fileobject, char *buffer);

uint32_t rust_SRCWRUTIL_GetSHA1_FilePath(const char *filename, char *buffer);

}  // extern "C"
