#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stddef.h>

struct SmolStringList;

extern "C" {

void rust_handle_destroy_SmolStringList(SmolStringList *object);

bool rust_handle_size_SmolStringList(SmolStringList *object, uint32_t *size);

uint32_t rust_SRCWRUTIL_GetSHA1_File(IFileObject *fileobject, char *buffer);

uint32_t rust_SRCWRUTIL_GetSHA1_FilePath(const char *filename, char *buffer);

}  // extern "C"
