[build]
target-dir = "_build"

# 2024... we can rely on CPUs to be using SSE2... not that it will likely change much in codegen...
rustflags = ["-Ctarget-feature=+sse2"]

target = "i686-pc-windows-msvc"

[target.i686-pc-windows-msvc]
# TODO: Do we want static crt on Windows? I can't remember if there was a reason for this...
rustflags = ["-Ctarget-feature=+sse2", "-Ctarget-feature=+crt-static", "-Cforce-frame-pointers=yes"]

