#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stddef.h>

extern "C" {

uint32_t rust_BZ2_XompressFile(const char *infile, const char *outfile, const char *infilefull, const char *outfilefull, int32_t compressionLevel, void *forward, int32_t data);

}  // extern "C"
